// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: getSingleChirp.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getSingleChirpByID = `-- name: GetSingleChirpByID :one
SELECT id, created_at, updated_at, body, user_id FROM chirps
WHERE $1 = id
`

func (q *Queries) GetSingleChirpByID(ctx context.Context, id uuid.UUID) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, getSingleChirpByID, id)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}
