// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: resetEmailAndPassword.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const resetEmailAndPassword = `-- name: ResetEmailAndPassword :one
UPDATE users
SET 
    email = $1,
    hashed_password = $2
WHERE 
    id = $3
RETURNING id, created_at, updated_at, email, hashed_password, is_chirpy_red
`

type ResetEmailAndPasswordParams struct {
	Email          string
	HashedPassword string
	ID             uuid.UUID
}

func (q *Queries) ResetEmailAndPassword(ctx context.Context, arg ResetEmailAndPasswordParams) (User, error) {
	row := q.db.QueryRowContext(ctx, resetEmailAndPassword, arg.Email, arg.HashedPassword, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}
