



POST http://localhost:8080/api/users

{
  "email": "anothertest@mail.com",
  "password": "jibberjabber"
}


###


POST http://localhost:8080/api/chirps	

{
  "body": "this is a test chirp",
  "user_id": "4eb853a7-eea0-4131-a34a-990a908d8e32"
}

###


POST http://localhost:8080/api/login

{
  "email": "anothertest@mail.com",
  "password": "jibberjabber"
}



###

GET http://localhost:8080/api/chirps/f0dcc40a-8155-4f7c-9add-8b2c1c27e60d

###

POST http://localhost:8080/api/refresh
Authorization: Bearer YOUR_refresh_code
Content-Type: application/json

{
  "key":"value"
}


###


POST http://localhost:8080/admin/reset





